{
 "title": "dg5R Dashboard",
 "tags": [
  "dg5R",
  "DLC"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "System Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server Overview",
   "type": "gapit-htmlgraphics-panel",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 1 },
   "options": {
    "reduceOptions": {
     "calcs": [
      "lastNotNull",
      "last",
      "firstNotNull",
      "first",
      "min",
      "max",
      "mean",
      "sum",
      "count",
      "range",
      "delta",
      "step",
      "diff",
      "logmin",
      "allIsZero",
      "allIsNull",
      "diffperc"
     ]
    }
   },
   "targets": [
    {
     "expr": "dlc_system_sensor{server=\"dg5R\"}",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  { "title": "Alert List", "type": "alertlist", "gridPos": { "h": 12, "w": 6, "x": 18, "y": 1 } },
  { "title": "Detailed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Cooling Health",
   "type": "gapit-htmlgraphics-panel",
   "gridPos": { "h": 20, "w": 7, "x": 0, "y": 14 },
   "options": {
    "reduceOptions": {
     "calcs": [
      "lastNotNull",
      "last",
      "firstNotNull",
      "first",
      "min",
      "max",
      "mean",
      "sum",
      "count",
      "range",
      "delta",
      "step",
      "diff",
      "logmin",
      "allIsZero",
      "allIsNull",
      "diffperc"
     ]
    }
   },
   "targets": [
    {
     "expr": "dlc_system_sensor{server=\"dg5R\", component=~\"cooling|environment\"}",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "Compute Health",
   "type": "gapit-htmlgraphics-panel",
   "gridPos": { "h": 20, "w": 11, "x": 7, "y": 14 },
   "options": {
    "reduceOptions": {
     "calcs": [
      "lastNotNull",
      "last",
      "firstNotNull",
      "first",
      "min",
      "max",
      "mean",
      "sum",
      "count",
      "range",
      "delta",
      "step",
      "diff",
      "logmin",
      "allIsZero",
      "allIsNull",
      "diffperc"
     ]
    }
   },
   "targets": [
    {
     "expr": "dlc_system_sensor{server=\"dg5R\", component=~\"cpu.*|gpu.*|memory\"}",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "Network Health",
   "type": "gapit-htmlgraphics-panel",
   "gridPos": { "h": 20, "w": 6, "x": 18, "y": 14 },
   "options": {
    "reduceOptions": {
     "calcs": [
      "lastNotNull",
      "last",
      "firstNotNull",
      "first",
      "min",
      "max",
      "mean",
      "sum",
      "count",
      "range",
      "delta",
      "step",
      "diff",
      "logmin",
      "allIsZero",
      "allIsNull",
      "diffperc"
     ]
    }
   },
   "targets": [
    {
     "expr": "dlc_system_sensor{server=\"dg5R\", component=\"network\", metric=\"link_status\"}",
     "legendFormat": "{{extra}}"
    },
    {
     "expr": "dlc_system_sensor{server=\"dg5R\", component=\"ib\", metric=\"temperature\"}",
     "legendFormat": "IB temp"
    }
   ]
  },
  { "title": "History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Coolant Temperature",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "dlc_system_sensor{server=\"dg5R\", component=\"cooling\", metric=~\"inlet[0-9]_temp|outlet[0-9]_temp|delta_t[0-9]\"}",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "Chassis Temperature & Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "dlc_system_sensor{server=\"dg5R\", component=\"environment\", metric=\"air_temp\"}",
     "legendFormat": "{{metric}}"
    },
    {
     "expr": "dlc_system_sensor{server=\"dg5R\", component=\"environment\", metric=\"air_humidity\"}",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "Memory Available %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dlc_system_sensor{server=\"dg5R\", component=\"memory\", metric=\"available\"} / ignoring(metric, unit) dlc_system_sensor{server=\"dg5R\", component=\"memory\", metric=\"total\"} * 100",
     "legendFormat": "Available %"
    }
   ]
  },
  {
   "title": "AI Processor Temperature",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "dlc_system_sensor{server=\"dg5R\", component=~\"gpu.\", metric=\"temperature\"}",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "AI Processor Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "dlc_system_sensor{server=\"dg5R\", component=~\"gpu.\", metric=\"power_current\"}",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "dlc_system_sensor{server=\"dg5R\", component=~\"cpu[0-9]\", metric=\"temperature\"}",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "CPU Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "dlc_system_sensor{server=\"dg5R\", component=~\"cpu[0-9]\", metric=\"power\"}",
     "legendFormat": "{{component}}"
    }
   ]
  }
 ]
}