modbus:
  port:
    - /dev/serial0
    - /dev/ttyUSB0
  baud:
    - 115200
    - 9600
  slave: 1
  parity: 'N'
  stopbits: 1
  bytesize: 8
  timeout_seconds: 1
loop:
  cycle_seconds: 1
pwm_freq:
  tim1: 1000
  tim2: 25000
  tim8: 25000
initial_pwm_duty:
  pump:
    ch1: 600
    ch2: 600
    ch3: 600
    ch4: 600
  fan:
    ch5: 0
    ch6: 0
    ch7: 0
    ch8: 0
    ch9: 0
    ch10: 1000
    ch11: 0
    ch12: 0
initial_dout_bitmask: 0
fan_curve:
  min_temp: 30
  max_temp: 50
  min_duty: 80
  max_duty: 1000
comm:
  timeout_after_failures: 3
  disconnected_after_failures: 10
pump:
  max_flow_lpm: 16
  flow_multiplier: 1.47
  min_duty: 500
  max_duty: 1000
wiring:
  ntc:
    inlet1: 13
    outlet1: 14
    outlet2: 15
    inlet2: 16
  din:
    level_bit: 0
  ain:
    leak_ch: 8
    leak_threshold_v: 2
  pulse:
    fan_tach_chs:
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
  pwm:
    pump_ch:
      - 1
      - 2
      - 3
      - 4
    fan_ch:
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
manual_pwm:
  pump:
    - 600
    - 600
    - 600
    - 600
  fan:
    - 214
    - 214
    - 214
    - 210
    - 214
    - 214
    - 210
    - 214
