{
 "title": "gadgetini",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Server OverView", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Coolant temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DLC_sensors_gauge{metric=\"Coolant temperature\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chassis temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DLC_sensors_gauge{metric=\"Air temperature\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chassis humidity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DLC_sensors_gauge{metric=\"Air humidity\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Current Server Alert", "type": "alertlist", "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 } },
  {
   "title": "Coolant level",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DLC_sensors_gauge{metric=\"Coolant level\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Leak detection ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min_over_time(DLC_sensors_gauge{metric=\"LEAK detection\"}[10s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chassis stability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DLC_sensors_gauge{metric=\"Chassis stability\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU temperature",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "DLC_sensors_gauge{\r\n  description=\"degree celcious\",\r\n  metric=~\"CPU[0-9]+ temperature\"\r\n}\r\n",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "Max CPU temperature (Last 24h)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(\r\n  label_replace(\r\n    DLC_sensors_gauge{\r\n      metric=~\"CPU[0-9]+ temperature\"\r\n    },\r\n    \"cpu_name\", \"CPU$1\",          \r\n    \"metric\", \"CPU([0-9]+) temperature\"\r\n  )[24h:]\r\n)\r\n",
     "legendFormat": "{{cpu_name}}"
    }
   ]
  },
  {
   "title": "Current CPU temperature",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\r\n    DLC_sensors_gauge{\r\n      metric=~\"CPU[0-9]+ temperature\"\r\n    },\r\n    \"cpu_name\", \"CPU$1\",          \r\n    \"metric\", \"CPU([0-9]+) temperature\"\r\n  )\r\n",
     "legendFormat": "{{cpu_name}}"
    }
   ]
  },
  {
   "title": "AI processor temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "clamp_max(label_replace(DLC_sensors_gauge{server_name=\"dg5W\", metric=~\".*asic temperature\"},\"id\",\"$1\",\"metric\",\"(.*) asic temperature\"),95)",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "Max AI processor temperature (Last 24h)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(label_replace(max_over_time(DLC_sensors_gauge{server_name=\"dg5W\", metric=~\".*asic temperature\"}[24h]),\"id\",\"$1\",\"metric\",\"(.*) asic temperature\"),95)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Current AI processor temperature ",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(label_replace(DLC_sensors_gauge{server_name=\"dg5W\", metric=~\".*asic temperature\"},\"id\",\"$1\",\"metric\",\"(.*) asic temperature\"),95)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "AI processor power",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "clamp_max(label_replace(DLC_sensors_gauge{metric=~\".*power usage.*\"},\"id\",\"$1\",\"metric\",\"(n300_[0-9]+[']).*power usage\"),300)",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "Max AI processor power (Last 24h)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(\r\n  label_replace(\r\n    DLC_sensors_gauge{\r\n      description=\"W\",\r\n      metric=~\"H200NVL_[0-9]+'current power usage\",\r\n      server_name=\"dg5W\"\r\n    },\r\n    \"gpu_name\", \"$1\",\r\n    \"metric\", \"(H200NVL_[0-9]+')current power usage\"\r\n  )[24h:]\r\n)\r\n",
     "legendFormat": "{{gpu_name}}"
    }
   ]
  },
  {
   "title": "Current AI processor power",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\r\n  DLC_sensors_gauge{\r\n    description=\"W\",\r\n    metric=~\"H200NVL_[0-9]+'current power usage\",\r\n    server_name=\"dg5W\"\r\n  },\r\n  \"gpu_name\", \"$1\",         \r\n  \"metric\", \"(H200NVL_[0-9]+')current power usage\"\r\n)\r\n",
     "legendFormat": "{{gpu_name}}"
    }
   ]
  },
  {
   "title": "Resource utilization",
   "type": "table",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DLC_sensors_gauge{\r\n  description=\"%\",\r\n  metric=\"CPU Usage\",\r\n  server_name=\"dg5W\"\r\n}\r\n",
     "legendFormat": "CPU usage"
    },
    {
     "expr": "100 *\r\nDLC_sensors_gauge{\r\n  description=\"GB\",\r\n  metric=\"Memory_usage\",\r\n  server_name=\"dg5W\"\r\n}\r\n/\r\nignoring(metric)\r\nDLC_sensors_gauge{\r\n  description=\"GB\",\r\n  metric=\"Memory_total\",\r\n  server_name=\"dg5W\"\r\n}\r\n",
     "legendFormat": "Memory usage"
    },
    {
     "expr": "100 *\r\nlabel_replace(\r\n  DLC_sensors_gauge{\r\n    description=\"byte\",\r\n    metric=~\"H200NVL_[0-9]+' current memory usage\",\r\n    server_name=\"dg5W\"\r\n  },\r\n  \"gpu_name\", \"$1\",                      \r\n  \"metric\", \"(H200NVL_[0-9]+') .*\"\r\n)\r\n/\r\non(server_name, gpu_name)\r\nlabel_replace(\r\n  DLC_sensors_gauge{\r\n    description=\"byte\",\r\n    metric=~\"H200NVL_[0-9]+' memory capacity\",\r\n    server_name=\"dg5W\"\r\n  },\r\n  \"gpu_name\", \"$1\",\r\n  \"metric\", \"(H200NVL_[0-9]+') .*\"\r\n)\r\n",
     "legendFormat": "{{gpu_name}} memory usage"
    }
   ]
  },
  {
   "title": "Current CPU utilization ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DLC_sensors_gauge{metric=\"CPU Usage\", server_name=\"dg5W\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current memory utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\nDLC_sensors_gauge{\r\n  description=\"GB\",\r\n  metric=\"Memory_usage\",\r\n  server_name=\"dg5W\"\r\n}\r\n/\r\nignoring(metric)\r\nDLC_sensors_gauge{\r\n  description=\"GB\",\r\n  metric=\"Memory_total\",\r\n  server_name=\"dg5W\"\r\n}\r\n",
     "legendFormat": "id:{{chip_id}}"
    }
   ]
  },
  {
   "title": "Current AI processors memory utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\r\nlabel_replace(\r\n  DLC_sensors_gauge{\r\n    description=\"byte\",\r\n    metric=~\"H200NVL_[0-9]+' current memory usage\",\r\n    server_name=\"dg5W\"\r\n  },\r\n  \"gpu_name\", \"$1\",                      \r\n  \"metric\", \"(H200NVL_[0-9]+') .*\"\r\n)\r\n/\r\non(server_name, gpu_name)\r\nlabel_replace(\r\n  DLC_sensors_gauge{\r\n    description=\"byte\",\r\n    metric=~\"H200NVL_[0-9]+' memory capacity\",\r\n    server_name=\"dg5W\"\r\n  },\r\n  \"gpu_name\", \"$1\",\r\n  \"metric\", \"(H200NVL_[0-9]+') .*\"\r\n)\r\n",
     "legendFormat": "{{gpu_name}}"
    }
   ]
  }
 ]
}