{
 "title": "gadgetini",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Server OverView", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Coolant temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DLC_sensors_gauge{metric=\"Coolant temperature\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chassis temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DLC_sensors_gauge{metric=\"Air temperature\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chassis humidity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DLC_sensors_gauge{metric=\"Air humidity\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Current Server Alert", "type": "candlestick", "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 } },
  {
   "title": "Coolant level",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DLC_sensors_gauge{metric=\"Coolant level\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Leak detection ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DLC_sensors_gauge{metric=\"LEAK detection\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chassis stability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DLC_sensors_gauge{metric=\"Chassis stability\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU temperature",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "DLC_sensors_gauge{metric=\"CPU temperature\"}",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "Max CPU temperature (Last 24h)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(DLC_sensors_gauge{metric=\"CPU temperature\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current CPU temperature",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DLC_sensors_gauge{metric=\"CPU temperature\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DLC_sensors_gauge{metric=\"CPU Usage\"}",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "Max CPU utilization (Last 24h)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max_over_time(DLC_sensors_gauge{metric=\"CPU CPU Usage\"}[1h])",
     "legendFormat": "__auto"
    },
    {
     "expr": "max_over_time(DLC_sensors_gauge{metric=\"CPU Usage\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current CPU utilization ",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DLC_sensors_gauge{metric=\"CPU Usage\", server_name=\"dg5W\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AI processor temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "DLC_sensors_gauge{description=\"degree celcious\", metric=~\".*asic temperature.*\"}",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "Max AI processor temperature (Last 24h)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\r\n    max_over_time(DLC_sensors_gauge{server_name=\"dg5W\", metric=~\".*asic temperature\"}[1h]),\r\n    \"id\",\r\n    \"$1\",\r\n    \"metric\",\r\n    \"(.*) asic temperature\"\r\n)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Current AI processor temperature ",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\r\n    DLC_sensors_gauge{server_name=\"dg5W\", metric=~\".*asic temperature\"},\r\n    \"id\",\r\n    \"$1\",\r\n    \"metric\",\r\n    \"(.*) asic temperature\"\r\n)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "AI processor power",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "DLC_sensors_gauge{description=\"W\", metric=~\".*power usage.*\"}",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "Max AI processor power (Last 24h)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\r\n    max_over_time(DLC_sensors_gauge{metric=~\".*power usage.*\"}[1h]),\r\n    \"id\",\r\n    \"$1\",\r\n    \"metric\",\r\n    \"(n300_[0-9]+[']).*power usage\"\r\n)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Current AI processor power",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\r\n    DLC_sensors_gauge{metric=~\".*power usage.*\"},\r\n    \"id\",\r\n    \"$1\",\r\n    \"metric\",\r\n    \"(n300_[0-9]+[']).*power usage\"\r\n)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\r\n    DLC_sensors_gauge{metric=\"Memory_usage\", server_name=\"dg5W\"}\r\n    / on(server_name)  \r\n    DLC_sensors_gauge{metric=\"Memory_total\", server_name=\"dg5W\"}\r\n) * 100",
     "legendFormat": "{{metric}}"
    }
   ]
  },
  {
   "title": "Max memory utilization (24h)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min_over_time(\r\n  DLC_sensors_gauge{description=\"GB\", server_name=\"dg5W\", metric=~\".*usage.*\"}[24h]\r\n)",
     "legendFormat": "id:{{chip_id}}"
    }
   ]
  },
  {
   "title": "Current memory utilization",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n    DLC_sensors_gauge{metric=\"Memory_usage\", server_name=\"dg5W\"}\r\n    / ignoring(metric)\r\n    DLC_sensors_gauge{metric=\"Memory_total\", server_name=\"dg5W\"}\r\n) * 100",
     "legendFormat": "id:{{chip_id}}"
    }
   ]
  }
 ]
}